## numpy practice session

In [1]:
import numpy as np

## Creating an array

In [2]:
# 1-D array
food = np.array(["samosa", "pakora", "raita"])
food

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [3]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [4]:
type(food)

numpy.ndarray

In [5]:
type(price)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
len(price)

3

In [8]:
price[2:]

array([5])

In [9]:
food[1]

np.str_('pakora')

In [10]:
price.mean()

np.float64(5.0)

In [11]:
# zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [14]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [16]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# table of 7
np.arange(7,77,7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [18]:
# line space
np.linspace(0,30, num=10)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [19]:
## specify your data type
np.ones(30, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.ones(30, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Array Functions

In [21]:
a = np.array([2, 5, 7, 320, 400, 4, 0.5, 4.5, 2.5, 100])
a

array([  2. ,   5. ,   7. , 320. , 400. ,   4. ,   0.5,   4.5,   2.5,
       100. ])

In [22]:
a.sort()
a

array([  0.5,   2. ,   2.5,   4. ,   4.5,   5. ,   7. , 100. , 320. ,
       400. ])

In [23]:
b = np.array([9.5, 34.6, 78, 90, 3.5])
b

array([ 9.5, 34.6, 78. , 90. ,  3.5])

In [24]:
c = np.concatenate((a, b))
c

array([  0.5,   2. ,   2.5,   4. ,   4.5,   5. ,   7. , 100. , 320. ,
       400. ,   9.5,  34.6,  78. ,  90. ,   3.5])

In [25]:
c.sort()
c

array([  0.5,   2. ,   2.5,   3.5,   4. ,   4.5,   5. ,   7. ,   9.5,
        34.6,  78. ,  90. , 100. , 320. , 400. ])

# 2-D Arrays

In [30]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [31]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [33]:
c = np.concatenate((a,b), axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [34]:
c = np.concatenate((a,b), axis=1)
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [35]:
x = np.array([[[1,2,3,4], [5,6,7,8]],
          [[1,2,3,4], [5,6,7,8]],
          [[1,2,3,4], [5,6,7,8]]])
x

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [36]:
# To find number of dimensions
x.ndim

3

In [37]:
y = np.array([[5,6,7],
             [5,6,7],
              [5,6,7,]])
y

array([[5, 6, 7],
       [5, 6, 7],
       [5, 6, 7]])

In [38]:
y.ndim

2

In [39]:
# size (number of elements)
x.size

24

In [40]:
y.size

9

In [42]:
x

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [43]:
# shape
x.shape

(3, 2, 4)

In [48]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [50]:
y = x.reshape(3,2)
y

array([[0, 1],
       [2, 3],
       [4, 5]])

In [55]:
np.reshape(x, newshape=(1,6), order="C")

C:\Users\SiliCon\AppData\Local\Temp\ipykernel_9032\1063790785.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(x, newshape=(1,6), order="C")


array([[0, 1, 2, 3, 4, 5]])

In [75]:
## convert 1D to 2D
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
# row wise 2D
b = a[np.newaxis, :]
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [77]:
# column wise 2D
c = a[:, np.newaxis]
c

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [78]:
a[0:11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
v = a*6
v

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [81]:
w = v.reshape(10,1)
w

array([[ 6],
       [12],
       [18],
       [24],
       [30],
       [36],
       [42],
       [48],
       [54],
       [60]])

In [82]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [85]:
a.sum()

np.int64(55)

In [86]:
a.mean()

np.float64(5.5)